In [14]:
l = [23245, 27, 546, 215 , -1234]

In [15]:
l

[23245, 27, 546, 215, -1234]

In [16]:
import numpy as np

In [17]:
np.array(l)

array([23245,    27,   546,   215, -1234])

In [18]:
a = np.array(l)

In [19]:
a

array([23245,    27,   546,   215, -1234])

In [20]:
b = np.array([12, 455, 63.3, True, "abc"])

In [21]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [22]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [23]:
l.pop()

-1234

In [24]:
l

[23245, 27, 546, 215]

In [25]:
a.mean()

4559.8

In [26]:
a

array([23245,    27,   546,   215, -1234])

In [27]:
l

[23245, 27, 546, 215]

In [28]:
l[1:]

[27, 546, 215]

In [29]:
l[0:2]

[23245, 27]

In [30]:
l[::2]

[23245, 546]

In [31]:
#---------------------

In [32]:
a

array([23245,    27,   546,   215, -1234])

In [33]:
a[2:]

array([  546,   215, -1234])

In [34]:
a[2:4]

array([546, 215])

In [35]:
b = a[2:4]

In [36]:
b

array([546, 215])

In [37]:
b[0]

546

In [38]:
b[:]

array([546, 215])

In [39]:
b[:] = 111

In [40]:
b

array([111, 111])

In [41]:
a

array([23245,    27,   111,   111, -1234])

In [42]:
c = a.copy()

In [43]:
c

array([23245,    27,   111,   111, -1234])

In [44]:
c[0] = 0

In [45]:
c

array([    0,    27,   111,   111, -1234])

In [46]:
a

array([23245,    27,   111,   111, -1234])